/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_appspot_apprtc_NDK_Hello */

#ifndef _Included_org_appspot_apprtc_NDK_Hello
#define _Included_org_appspot_apprtc_NDK_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_appspot_apprtc_NDK_Hello
 * Method:    GetInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_appspot_apprtc_NDK_Hello_GetInt
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
